Php8.1 compatibility
dadajuice/zephyrus pull request #13
Opened 2021-11-30 15:20 UTC by Lacni135

Multiple commit to remove deprecated stuff from php8.1
-  date/time format are now hardcoded to prevent breaking previous format specified inside config.ini. When ready to make the change, take the format inside the new class and paste inside config.ini

2021-11-30 15:22 UTC, Lacni135 commented
for the date/time format, a patch could be done to check if a '%' is detected inside the format string and default to the new format. This would prevent breaking backward compatibility and also allow the new format to be written inside the config.ini

2022-01-06 15:31 UTC, dadajuice requested changes
The `mark` method needs to be more flexible by accepting null argument (e.g. Pug rendering using the mark method on null field must not break and also not force user to add unnecessary ifs around statement).

Maybe a simple fix would be to make sure the `if (empty($data))` part work properly. Technically, NULL argument should be considered "empty" and thus shall not reach the `preg_replace`. If this is not working, maybe adding `|| is_null($data)` to the condition would do the trick.

2022-01-06 15:34 UTC, dadajuice reviewed
Cannot use third part fork within the framework.

2022-01-06 15:40 UTC, dadajuice approved these changes

2022-01-06 15:47 UTC, closed without merging